// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyByeOrW1tX3mtVWl3xSFE0UAuzA3WKj7GM',
    appId: '1:392134002631:web:71b610da894552e870fbe2',
    messagingSenderId: '392134002631',
    projectId: 'chat-application-453b4',
    authDomain: 'chat-application-453b4.firebaseapp.com',
    storageBucket: 'chat-application-453b4.appspot.com',
    measurementId: 'G-H9559RJC54',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAxZrMSoJbWvWaELjZbBMgo2Z8BuwusCGQ',
    appId: '1:392134002631:android:0097456ceffcac6270fbe2',
    messagingSenderId: '392134002631',
    projectId: 'chat-application-453b4',
    storageBucket: 'chat-application-453b4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBFCwVgFMtAHip3oau7ykidkH0RoNNphl8',
    appId: '1:392134002631:ios:1beb31a2d1a5c75270fbe2',
    messagingSenderId: '392134002631',
    projectId: 'chat-application-453b4',
    storageBucket: 'chat-application-453b4.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBFCwVgFMtAHip3oau7ykidkH0RoNNphl8',
    appId: '1:392134002631:ios:1beb31a2d1a5c75270fbe2',
    messagingSenderId: '392134002631',
    projectId: 'chat-application-453b4',
    storageBucket: 'chat-application-453b4.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyByeOrW1tX3mtVWl3xSFE0UAuzA3WKj7GM',
    appId: '1:392134002631:web:c1c03d6f6725f50a70fbe2',
    messagingSenderId: '392134002631',
    projectId: 'chat-application-453b4',
    authDomain: 'chat-application-453b4.firebaseapp.com',
    storageBucket: 'chat-application-453b4.appspot.com',
    measurementId: 'G-L3XW2BR8VE',
  );
}
